"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](fg:#9A348E bg:#DA627D)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$nodejs\
$python\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$aws\
[](fg:#06969A bg:#33658A)\
$cmd_duration\
[](fg:#33658A)\
$line_break\
$character
"""


[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true


[directory]
style = "bg:#DA627D"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "


[git_branch]
style = "bg:#FCA17D"
format = '[$symbol$branch]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind]($style)'

[aws]
style = "bg:#06969A"
format = '[$symbol($profile)(\($region\))]($style)'

[cmd_duration]
style = "bg:#33658A"
format = '[󰔟 $duration]($style)'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"


[c]
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[golang]
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[nodejs]
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[python]
style = "bg:#86BBD8"
format = '[$symbol($version)(\($virtualenv\))]($style)'

[rust]
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'
